services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true


  Pumukit\StatsUIBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]

